#Block executable
EXECUTABLE=signal_generator

#Source files to compile executable
SRCS=signal_generator.c signal_generator_settings.c
INCLUDES=#sources in ~/.xenomailab/include

#Custom compiler flags
MY_CFLAGS=#compiler e.g. -Werror
MY_LDFLAGS=#linking e.g. -lparapin

include ../../include/global.mk
