### List of applications to be build
EXECUTABLE=gain

#Source files
SRCS=gain.c gain_settings.c
INCLUDES=#sources in ~/.xenomailab/include

#Custom flags
MY_CFLAGS=#compiler e.g. -Werror
MY_LDFLAGS=#libs e.g. -lparapin

include ../../include/Makefile
