#############################################################################
# Makefile for building: XenomaiLab
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon Nov 14 16:29:46 2011
# Project:  XenomaiLab.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile XenomaiLab.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Wno-deprecated -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		diagramitem.cpp \
		diagramscene.cpp \
		diagramtextitem.cpp \
		arrow.cpp \
		blockdiagram.cpp \
		block.cpp \
		processresult.cpp \
		settings.cpp \
		strmap.cpp \
		mtrx.c \
		line.cpp \
		filesettings.cpp \
		projectfile.cpp \
		blockregistry.cpp \
		superblock.cpp \
		workspace.cpp \
		superline.cpp \
		linepath.cpp moc_mainwindow.cpp \
		moc_diagramscene.cpp \
		moc_diagramtextitem.cpp \
		moc_blockdiagram.cpp \
		moc_block.cpp \
		qrc_xenomailab.cpp
OBJECTS       = main.o \
		mainwindow.o \
		diagramitem.o \
		diagramscene.o \
		diagramtextitem.o \
		arrow.o \
		blockdiagram.o \
		block.o \
		processresult.o \
		settings.o \
		strmap.o \
		mtrx.o \
		line.o \
		filesettings.o \
		projectfile.o \
		blockregistry.o \
		superblock.o \
		workspace.o \
		superline.o \
		linepath.o \
		moc_mainwindow.o \
		moc_diagramscene.o \
		moc_diagramtextitem.o \
		moc_blockdiagram.o \
		moc_block.o \
		qrc_xenomailab.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/static.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		XenomaiLab.pro
QMAKE_TARGET  = XenomaiLab
DESTDIR       = 
TARGET        = XenomaiLab

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: XenomaiLab.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/static.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile XenomaiLab.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/static.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile XenomaiLab.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/XenomaiLab1.0.0 || $(MKDIR) .tmp/XenomaiLab1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/XenomaiLab1.0.0/ && $(COPY_FILE) --parents mainwindow.h diagramitem.h diagramscene.h diagramtextitem.h arrow.h blockdiagram.h block.h processresult.h settings.h strmap.h mtrx.h line.h filesettings.h projectfile.h blockregistry.h superblock.h workspace.h superline.h linepath.h macros.h .tmp/XenomaiLab1.0.0/ && $(COPY_FILE) --parents xenomailab.qrc .tmp/XenomaiLab1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp diagramitem.cpp diagramscene.cpp diagramtextitem.cpp arrow.cpp blockdiagram.cpp block.cpp processresult.cpp settings.cpp strmap.cpp mtrx.c line.cpp filesettings.cpp projectfile.cpp blockregistry.cpp superblock.cpp workspace.cpp superline.cpp linepath.cpp .tmp/XenomaiLab1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/XenomaiLab1.0.0/ && (cd `dirname .tmp/XenomaiLab1.0.0` && $(TAR) XenomaiLab1.0.0.tar XenomaiLab1.0.0 && $(COMPRESS) XenomaiLab1.0.0.tar) && $(MOVE) `dirname .tmp/XenomaiLab1.0.0`/XenomaiLab1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/XenomaiLab1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_diagramscene.cpp moc_diagramtextitem.cpp moc_blockdiagram.cpp moc_block.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_diagramscene.cpp moc_diagramtextitem.cpp moc_blockdiagram.cpp moc_block.cpp
moc_mainwindow.cpp: superline.h \
		macros.h \
		workspace.h \
		filesettings.h \
		superblock.h \
		settings.h \
		strmap.h \
		blockregistry.h \
		diagramitem.h \
		projectfile.h \
		processresult.h \
		blockdiagram.h \
		line.h \
		mtrx.h \
		block.h \
		diagramscene.h \
		diagramtextitem.h \
		linepath.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_diagramscene.cpp: diagramitem.h \
		superblock.h \
		macros.h \
		diagramtextitem.h \
		blockdiagram.h \
		superline.h \
		line.h \
		mtrx.h \
		block.h \
		processresult.h \
		linepath.h \
		diagramscene.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) diagramscene.h -o moc_diagramscene.cpp

moc_diagramtextitem.cpp: diagramtextitem.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) diagramtextitem.h -o moc_diagramtextitem.cpp

moc_blockdiagram.cpp: superline.h \
		macros.h \
		line.h \
		mtrx.h \
		block.h \
		processresult.h \
		blockdiagram.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) blockdiagram.h -o moc_blockdiagram.cpp

moc_block.cpp: macros.h \
		processresult.h \
		block.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) block.h -o moc_block.cpp

compiler_rcc_make_all: qrc_xenomailab.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_xenomailab.cpp
qrc_xenomailab.cpp: xenomailab.qrc \
		images/bold.png \
		images/italic.png \
		images/background2.png \
		images/bringtofront.png \
		images/background3.png \
		images/underline.png \
		images/background4.png \
		images/linepointer.png \
		images/delete.png \
		images/linecolor.png \
		images/background1.png \
		images/pointer.png \
		images/textpointer.png \
		images/floodfill.png \
		images/sendtoback.png
	/usr/bin/rcc -name xenomailab xenomailab.qrc -o qrc_xenomailab.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp line.h \
		mtrx.h \
		mainwindow.h \
		superline.h \
		macros.h \
		workspace.h \
		filesettings.h \
		superblock.h \
		settings.h \
		strmap.h \
		blockregistry.h \
		diagramitem.h \
		projectfile.h \
		processresult.h \
		blockdiagram.h \
		block.h \
		diagramscene.h \
		diagramtextitem.h \
		linepath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		superline.h \
		macros.h \
		workspace.h \
		filesettings.h \
		superblock.h \
		settings.h \
		strmap.h \
		blockregistry.h \
		diagramitem.h \
		projectfile.h \
		processresult.h \
		blockdiagram.h \
		line.h \
		mtrx.h \
		block.h \
		diagramscene.h \
		diagramtextitem.h \
		linepath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

diagramitem.o: diagramitem.cpp diagramitem.h \
		superblock.h \
		macros.h \
		linepath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diagramitem.o diagramitem.cpp

diagramscene.o: diagramscene.cpp diagramscene.h \
		diagramitem.h \
		superblock.h \
		macros.h \
		diagramtextitem.h \
		blockdiagram.h \
		superline.h \
		line.h \
		mtrx.h \
		block.h \
		processresult.h \
		linepath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diagramscene.o diagramscene.cpp

diagramtextitem.o: diagramtextitem.cpp diagramtextitem.h \
		diagramscene.h \
		diagramitem.h \
		superblock.h \
		macros.h \
		blockdiagram.h \
		superline.h \
		line.h \
		mtrx.h \
		block.h \
		processresult.h \
		linepath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diagramtextitem.o diagramtextitem.cpp

arrow.o: arrow.cpp arrow.h \
		diagramitem.h \
		superblock.h \
		macros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arrow.o arrow.cpp

blockdiagram.o: blockdiagram.cpp blockdiagram.h \
		superline.h \
		macros.h \
		line.h \
		mtrx.h \
		block.h \
		processresult.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blockdiagram.o blockdiagram.cpp

block.o: block.cpp block.h \
		macros.h \
		processresult.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o block.o block.cpp

processresult.o: processresult.cpp processresult.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o processresult.o processresult.cpp

settings.o: settings.cpp settings.h \
		strmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

strmap.o: strmap.cpp strmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o strmap.o strmap.cpp

mtrx.o: mtrx.c mtrx.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o mtrx.o mtrx.c

line.o: line.cpp line.h \
		mtrx.h \
		macros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o line.o line.cpp

filesettings.o: filesettings.cpp filesettings.h \
		superline.h \
		macros.h \
		superblock.h \
		settings.h \
		strmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filesettings.o filesettings.cpp

projectfile.o: projectfile.cpp projectfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectfile.o projectfile.cpp

blockregistry.o: blockregistry.cpp blockregistry.h \
		diagramitem.h \
		superblock.h \
		macros.h \
		filesettings.h \
		superline.h \
		settings.h \
		strmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blockregistry.o blockregistry.cpp

superblock.o: superblock.cpp superblock.h \
		macros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o superblock.o superblock.cpp

workspace.o: workspace.cpp workspace.h \
		filesettings.h \
		superline.h \
		macros.h \
		superblock.h \
		settings.h \
		strmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o workspace.o workspace.cpp

superline.o: superline.cpp superline.h \
		macros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o superline.o superline.cpp

linepath.o: linepath.cpp linepath.h \
		macros.h \
		diagramitem.h \
		superblock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linepath.o linepath.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_diagramscene.o: moc_diagramscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diagramscene.o moc_diagramscene.cpp

moc_diagramtextitem.o: moc_diagramtextitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diagramtextitem.o moc_diagramtextitem.cpp

moc_blockdiagram.o: moc_blockdiagram.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_blockdiagram.o moc_blockdiagram.cpp

moc_block.o: moc_block.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_block.o moc_block.cpp

qrc_xenomailab.o: qrc_xenomailab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_xenomailab.o qrc_xenomailab.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

