#Block executable
EXECUTABLE=plant

#Source files to compile executable
SRCS=plant.c plant_settings.c
INCLUDES=#sources in ~/.xenomailab/include

#Custom compiler flags
MY_CFLAGS=#compiler e.g. -Werror
MY_LDFLAGS=#linking e.g. -lparapin

include ../../include/global.mk
