#Block executable
EXECUTABLE=Z

#Source files to compile executable
SRCS=Z.c Z_settings.c
INCLUDES=#sources in ~/.xenomailab/include

#Custom compiler flags
MY_CFLAGS=#compiler e.g. -Werror
MY_LDFLAGS=#linking e.g. -lparapin

include ../../include/global.mk
